### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by maaudrana** [aliwaris0572/CustomCamera#2]
Hallo
 Great to know about this projects.I am a designer want to make a logo  for this projects app,if you have any requirements then let me know.Its free for any open source projects.

**Comment by aliwaris0572** [comment]
Sure, every contribution is welcomed. 👍

**Comment by maaudrana** [comment]
Hallo sir why closed this ? I am working on that.

**Comment by maaudrana** [comment]
I have created three logos for you, which one of your choice tells me that I'll give you that source file. If you think something needs to be changed then you can tell me I'll change.

![customcamera-01](https://user-images.githubusercontent.com/34313493/40705674-569a1f58-640d-11e8-81c3-8ec2d56649e9.jpg)

**Comment by aliwaris0572** [comment]
The third one looks good but it should be more meaning-centric (about the library ability to control the megapixels and scale the captured image).

**Comment by maaudrana** [comment]
which one of your choice tells me that I'll give you that source file. If you think something needs to be changed then you can tell me I'll change.

![eee-01](https://user-images.githubusercontent.com/34313493/40707813-9656e814-6413-11e8-8945-8a53ec0de62a.jpg)

**Comment by aliwaris0572** [comment]
Last one looks good.

**Comment by maaudrana** [comment]
Can i open a pr now?

**Comment by maaudrana** [comment]
plz check sir #3

**Comment by maaudrana** [comment]
All the source file of the logo uploaded to google 
<a href="https://drive.google.com/drive/folders/1pT3xywopvEMTAGrlct8Yo_rDY64B3lEl?usp=sharing">drive</a>
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

**Comment by aliwaris0572** [comment]
@maaudrana You are free to contribute logos here as well:
[CustomSearch library](https://github.com/aliwaris0572/CustomSearch)

**Comment by masudr4n4** [comment]
sure. thank you

**Comment by TacoTheDank** [comment]
Checked to see if original icons were stolen; they were not

I'm glad to see people creating their own things, thank you for being an honest creator :)

(bringing this up because i had to fight (for days) with two accounts that were stealing icons from flaticons and trying to pass them off as their own (they were actually the same person lol))

**Comment by masudr4n4** [comment]
Haha.you are welcome @TacoTheDank 
Stole someone works is not right way to learn more.
I tried my best to give attention to my works and their is no chance to stole someone's work to me.
