### ISSUE TITLE
Custom Layout 

### ISSUE THREAD

**Issue by Sufyan255** [aliwaris0572/CustomCamera#4]
hi sir, there is no custom layout for camera surface. You made this custom screen but not used in project. Are you working on custom camera layout? Default camera used in project

**Comment by aliwaris0572** [comment]
Earlier, I used custom layout for camera, but there were some issues with saving images on different devices. So, for now, I switched to default camera layout. If you are interested to work on the custom layout, you are free to fork it. 👍
